---
AWSTemplateFormatVersion: '2010-09-09'
Description: "Public Applcation Load Balancer"
Parameters:
  DomainName:
    Description: A fully-qualified domain name.
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '^(\*\.)?(((?!-)[A-Za-z0-9-]{0,62}[A-Za-z0-9])\.)+((?!-)[A-Za-z0-9-]{1,62}[A-Za-z0-9])$'
    ConstraintDescription: must be a valid fully-qualified domain name.
    Default: '*.prosupport.in'
  HostedZoneId:
    Description: Provide your public hosted zone ID.
    Type: String
Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId
