---
Parameters:
  TrustedAccount:
    Type: String
    Description: Your account id, to be trusted by the user
Resources:
  CrossAccountRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            AWS:
              Fn::Sub: arn:aws:iam::${TrustedAccount}:root
          Sid: ''
        Version: '2012-10-17'
      Path: "/"
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - route53:*
            - route53domains:*
            Effect: Allow
            Resource: "*"
          Version: '2012-10-17'
        PolicyName: CustomerAccountAccess
Outputs:
  CrossAccountRole:
    Description: Cross Account Role
    Value:
      Ref: CrossAccountRole
    
