AWSTemplateFormatVersion: '2010-09-09'
Description: A CloudFormation template for creating a Hosted Zone in Route53.
Parameters:
  Name:
    Description: A fully-qualified domain name.
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: "(?!-)[a-zA-Z0-9-.]*(?<!-)"
    ConstraintDescription: must be a valid fully-qualified domain name.
    Default: 'prosupport.in'
  Comment:
    Description: An optinal comment about the hosted zone.
    Type: String
    MinLength: '1'
    MaxLength: '255'
    AllowedPattern: "[-_ a-zA-Z0-9]*"
    ConstraintDescription: can contain only alphanumeric characters, spaces, dashes
      and underscores.
    Default: Created for public DNS resolution
Resources:
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: ''
      Name:
        Ref: Name
      HostedZoneTags:
      - Key: StackName
        Value:
          Ref: AWS::StackName
Outputs:
  HostedZoneName:
    Description: The fully-qualified domain name.
    Value:
      Ref: Name
  HostedZoneID:
    Description: The ID of the Hosted Zone.
    Value:
      Ref: HostedZone
